databaseChangeLog:
  - changeSet:
      id: 1
      author: author_name
      changes:
        - createTable:
            tableName: users
            columns:
              - column:
                  name: id
                  type: SERIAL
                  constraints:
                    primaryKey: true
              - column:
                  name: username
                  type: VARCHAR(255)
              - column:
                  name: password
                  type: VARCHAR(255)
              - column:
                  name: email
                  type: VARCHAR(255)
              - column:
                  name: role
                  type: VARCHAR(255)
              - column:
                  name: firstName
                  type: VARCHAR(255)
              - column:
                  name: lastName
                  type: VARCHAR(255)
              - column:
                  name: phoneNumber
                  type: VARCHAR(255)
              - column:
                  name: address
                  type: VARCHAR(255)
              - column:
                  name: city
                  type: VARCHAR(255)
              - column:
                  name: postalCode
                  type: VARCHAR(255)
              - column:
                  name: country
                  type: VARCHAR(255)
              - column:
                  name: instagram
                  type: VARCHAR(255)
              - column:
                  name: trainings
                  type: VARCHAR(255)
              - column:
                  name: circuits
                  type: VARCHAR(255)
              - column:
                  name: weight
                  type: VARCHAR(255)
  - changeSet:
      id: 2
      author: author_name
      changes:
        - createSequence:
            sequenceName: user_seq
            startValue: 1
  - changeSet:
      id: 3
      author: author_name
      changes:
        - createTable:
            tableName: trainings
            columns:
              - column:
                  name: id
                  type: SERIAL
                  constraints:
                    primaryKey: true
              - column:
                  name: name
                  type: VARCHAR(255)
              - column:
                  name: description
                  type: VARCHAR(255)
              - column:
                  name: type
                  type: VARCHAR(255)
              - column:
                  name: level
                  type: VARCHAR(255)
              - column:
                  name: duration
                  type: VARCHAR(255)
              - column:
                  name: equipment
                  type: VARCHAR(255)
              - column:
                  name: exercises
                  type: VARCHAR(255)
              - column:
                  name: imageUrl
                  type: VARCHAR(255)
              - column:
                  name: trainer
                  type: VARCHAR(255)
              - column:
                  name: category
                  type: VARCHAR(255)
              - column:
                  name: calories
                  type: VARCHAR(255)
              - column:
                  name: comments
                  type: VARCHAR(255)
              - column:
                  name: date
                  type: VARCHAR(255)
              - column:
                  name: time
                  type: VARCHAR(255)
              - column:
                  name: location
                  type: VARCHAR(255)
              - column:
                  name: price
                  type: VARCHAR(255)
              - column:
                  name: status
                  type: VARCHAR(255)
              - column:
                  name: participants
                  type: VARCHAR(255)
              - column:
                  name: maxParticipants
                  type: VARCHAR(255)
              - column:
                  name: rating
                  type: VARCHAR(255)
              - column:
                  name: reviews
                  type: VARCHAR(255)
              - column:
                  name: trainerId
                  type: VARCHAR(255)
              - column:
                  name: quality
                  type: VARCHAR(255)
              - column:
                  name: progress
                  type: VARCHAR(255)
  - changeSet:
      id: 4
      author: author_name
      changes:
        - createSequence:
            sequenceName: trainings_seq
            startValue: 1
